version: '3.8'

services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=${DATABASE_HOST}
    ports:
      - "5432:5432"
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres

networks:
  default:
    driver: bridge

volumes:
  postgres_data: {}